### ISSUE TITLE
Call to undefined method SilverStripe\Config\Collections\CachedConfigCollection::remove() 

### ISSUE THREAD

**Issue by lars-lemon8** [Cyber-Duck/Silverstripe-SEO#19]
Could you re-open https://github.com/Cyber-Duck/Silverstripe-SEO/issues/13 ?

**Comment by Andrew-Mc-Cormack** [comment]
Fixed with this I believe - https://github.com/Cyber-Duck/Silverstripe-SEO/commit/7a094cf70b4ab1558e4ff2709179844c61a43dbd

**Comment by albanyacademy** [comment]
issue still present in ^4.2, it was only fixed on the develop branch

**Comment by Dennisprins93** [comment]
I Made a pull request @albanyacademy to merge it into master. I'm also waiting for this to get fixed. 
See Pull https://github.com/Cyber-Duck/Silverstripe-SEO/pull/24
